name: Pull Requests

on:
  pull_request:
    branches:
    - '*'

env:
  solution: 'FluentMigrator.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: Debug

  # Enable containers for integration tests
  FM_TestConnectionStrings__MySql__ContainerEnabled: true
  FM_TestConnectionStrings__MySql__IsEnabled: true
  FM_TestConnectionStrings__Oracle__ContainerEnabled: true
  FM_TestConnectionStrings__Oracle__IsEnabled: true
  FM_TestConnectionStrings__Postgres__ContainerEnabled: true
  FM_TestConnectionStrings__Postgres__IsEnabled: true
  FM_TestConnectionStrings__SqlServer2016__ContainerEnabled: true
  FM_TestConnectionStrings__SqlServer2016__IsEnabled: true
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        dotnet-version: [ '8.0.x', '9.0.x' ]

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: true

    - name: Setup dotnet 9.0.x
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - run: dotnet restore ${{ env.solution }}
    - run: dotnet build '${{ env.solution }}' --no-restore --property:configuration='${{ env.buildConfiguration }}' --property:platform='${{ env.buildPlatform }}' --property:Version="${{ github.run_number }}"

    - name: Run tests and collect results
      uses: zyborg/dotnet-tests-report@v1
      with:
        project_path: ${{ env.solution }}
        report_name: FluentMigratorTests
        report_title: FluentMigrator Tests
        github_token: ${{ secrets.GITHUB_TOKEN }}
        no_restore: true
        no_build: true
        msbuild_configuration: ${{ env.buildConfiguration }}
        skip_check_run: true
        fail_build_on_failed_tests: true
        gist_name: FluentMigratorTests.md
        gist_token: ${{ secrets.GIST_TOKEN }}
#
#    - name: VSTest
#      run: |
#        dotnet tool install --global coverlet.console
#        # Coverlet recommends publishing the Tests in order to support XPlat Code Coverage.
#        dotnet publish test/FluentMigrator.Tests/FluentMigrator.Tests.csproj --framework net8.0
#        dotnet test test/FluentMigrator.Tests/bin/${{ env.buildConfiguration }}/net8.0/FluentMigrator.Tests.dll --collect:"XPlat Code Coverage;Format=opencover"
#      shell: bash
#    - uses: actions/upload-artifact@v4
#      with:
#        path: ${{ github.workspace }}
#        name: drop
